### PR TITLE
Reverse order of Style lookup in AbstractElement.getProperty.

### PR DESCRIPTION
**Pull request by rjcohn**
Look in styles for a property in the reverse order the Styles are added. This enables a client to
add a new Style to an Element that can override the effect of previously added Styles. Otherwise
there is no way to change the property using a Style without changing the underlying Style.  The
lookup order doesn't seem to be documented anywhere, so while this is an incompatible change, it
doesn't seem to affect the documentation.
The existing tests of addStyle in StylesTest are unaffected, but the new test would have failed with
the old code.

### CODE REVIEW

**Comment by blagae** [comment]
Hi @rjcohn,

Thank you for your contribution. Since this would indeed be a technically backwards-incompatible change, we cannot accept it as-is for our upcoming (minor) release. However, we will look into an elegant solution to implement your proposed functionality without breaking backwards compatibility, because it definitely solves a problem and the current iteration behavior was not a deliberate design decision.

We will keep you posted on our progress.

**Comment by rjcohn** [comment]
While I understand, I refer you to this story:
https://beebo.org/haycorn/2015-04-20_tabs-and-makefiles.html

**Comment by blagae** [comment]
Hi @rjcohn,

So we decided to go from a declaration of a `Set<>` to a `Collection<>` to minimize the backwards incompatibility, and just make the (default) runtime type a `LinkedList`, and we just add some logic for which iterator to call. That seemed most elegant to us.

But anyway, it looks like you decided to revert your commit. Could you explain your reason for that ?

Thanks,
Benoit

**Comment by rjcohn** [comment]
Sorry. I realized that I hadn't put this pull request on a feature branch, and I was trying to clean things up so that I could do more pull requests without this code getting in the way. Please ignore the revert.
If I understand your proposal, getProperty will work as I suggested, but someone could use a different Collection to get the old behavior? I'm happy with that.

**Comment by blagae** [comment]
Hi @rjcohn,

I have rebased your pull request code on top of HEAD in commit https://github.com/itext/itext7/commit/1ede28c13dfb072970f035ae57e3c4e6be267cd2 and then added my refactoring in https://github.com/itext/itext7/commit/59cb20753c12ae676dec308130c4a2cb3e8ebd6c

Github only picks up on merges to autoclose pull requests, but we prefer to rebase in order to avoid merge commits. That means that I will have to close the pull request manually, but the code has been added to the repository anyway. You are still the author of the commit, so the work is properly attributed to you.

**Pull request closed without merging**
