### PR TITLE
itext7 support sm3withsm2 signature 

### PR DESCRIPTION
**Pull request by hanksandy**
SM2 signature is used by more and more use in China, and BouncyCastle has also supported SM2/SM3 algorithm. It is hoped that iText can also support SM2 signature.
At present, there are several ways of PDF signature. I implement mode 2 and mode 3. At present, I submit mode 2.

mode1:  RSA: original - > sha256withrsa - > pkcs#7
mode2:  SM2: original - > sm3withsm2 - > pkcs#7
mode3:  SM2: original - > sm3withsm2 - > gb38540

### CODE REVIEW

**Comment by michaeldemey** [comment]
Hi,

Thank you for your patience in our handling of this PR. I do think this PR looks very interesting, but there's a few steps we need to go over before we can get this merged.

As a first step, can you squash all your commits into one commit? Makes it easier for us to review this and rebase/handle conflicts.

Kind regards,
Michaël.

**Comment by michaeldemey** [comment]
I'm trying to reopen this PR, but I can't because there are no new commits. Could you look into getting your code into the PR?

**Comment by AnhelinaM** [comment]
Hello @HankoZhou! I have created a sample code using `8.0.3-SNAPSHOT` itext version, but we cannot validate SM3WithSM2 signature, could you please take a look at the sample code and the output pdf in the archive I attached to check if it's ok?
[SM3WithSM2Sample.zip](https://github.com/itext/itext7/files/13034102/SM3WithSM2Sample.zip)

P.S. I used `tongsuo` tool to create private key and certificate for that sample, but it would be great if you could share other ways to create such a certificate and maybe tools for validating SM3WithSM2 PDF signatures 🙂

**Comment by 1350493353** [comment]
version is 8.0.3 ,also tried other version 
Why do I still prompt
Signing algorithms SM3withSM2 and SM2 are not supported.
Please help me,thanks

**Comment by linxd** [comment]
DETAILS:	Wrapped java.security.NoSuchAlgorithmException: SM3

**Pull request closed without merging**
