### PR TITLE
Render text element background opacity

### PR DESCRIPTION
**Pull request by StefRe**
Make setBackgroundColor with opacity work for text elements. Background
opacity used to be honored only for paragraph elements, not for text
elements inside a paragraph. This PR renders transparent backgrounds for
text elements.
See also https://stackoverflow.com/questions/55005898/itext-background-opacity.

### CODE REVIEW

**Comment by blagae** [comment]
Hi @StefRe ,

At first sight, the changes look very good and your fix solves the problem in a concise manner. Can you also add a few test cases with illegal parameter values for opacity ? e.g. 200, NaN, -1, ...

If you don't feel like doing that, then we can look into doing it on our end.

**Comment by StefRe** [comment]
Here you go. Added tests for illegal parameters. The opacity parameter range gets clipped to [0, 1] with NaN treated as fully opaque.

**Comment by blagae** [comment]
Perfect, thanks. The PR will not be merged on Github because we have an internal test pipeline & merging process, but it will get into develop very soon and then I will close the PR. The commits will still be under your name.

Thank you for your contribution !

**Comment by blagae** [comment]
Hi @StefRe ,

Apparently Github picks up on fast-forward merges, so this PR was closed automatically.

Thank you for your contribution !
Benoit

**Pull request merged**
