### PR TITLE
Add page sizes that were available in iText 5

### PR DESCRIPTION
**Pull request by amedee**
I have also updated the .gitignore file, to properly attribute authorship depending on in which context I write code.

### CODE REVIEW

**Comment by amedee** [comment]
Hello iText Software, I didn't add any tests for this change, because it's basically just adding a couple of constants.
I hope that's ok?

**Comment by pratikbutani** [comment]
You can give page size in the Document object.

`Document document = new Document(pdfDocument, PageSize.A4, true);`

**Comment by amedee** [comment]
@pratikbutani That is correct, and that is exactly the intent of this PR.
In your example, you use the constant `PageSize.A4`.
iText 5 had a longer list of PageSize constants, and this PR re-introduces them to iText 7.

**Comment by amedee** [comment]
Hello iText Software, I submitted this pull request 49 days ago, and I haven't gotten any feedback yet through GitHub.
Is there anything I can do to improve my pull request? What can I do to help you with the review? Any other communication channel I should use to discuss the pull request?

**Comment by amedee** [comment]
Hello iText Software, I'd like to give another bump to this PR. Haven't heard anything yet since last month.

**Pull request closed without merging**
