### PR TITLE
Add support for recently published ISO extensions to digital signing

### PR DESCRIPTION
**Pull request by MatthiasValvekens**
(Warning: this is a relatively big contribution, but the vast majority of the changes are local to the `sign` module)

ISO published ISO/TS 32001 and ISO/TS 32002 in September and October, respectively. These technical specifications extend PDF's digital signing capabilities in the following ways:

 - ISO/TS 32001: support for SHA-3 hash functions
 - ISO/TS 32002: list of supported ECDSA curves + EdDSA support

This PR adds support for these two extensions to iText (both signing & validation) without breaking API compatibility. Here's a rough overview of the changes:

 - I cleaned house in the internals of `PdfPKCS7` and `PrivateKeySignature` and renamed a bunch of variables and private fields so it's easier to tell what they actually represent (especially now that the number of supported algorithms is rising). I didn't touch the public API other than rewriting some Javadoc snippets, but I strongly recommend doing away with the old naming scheme at the next opportunity (i.e. major version upgrade).
 - I also fixed a long-standing and oft-complained-about bug in the ECDSA handler (DEVSIX-4842): iText currently writes wrong OIDs in all ECDSA signatures. For ECDSA, there is no generic signature algorithm OID, but only OIDs that also encode the relevant digest algorithm. In fact, the exact same problem was present for DSA signatures as well. Not that anyone still cares about plain old DSA, but I fixed that too.
 - The ISO documents require registering extensions in the developer extensions dictionary, and in fact they require a multivalued developer extension prefix. This is a feature exclusive to the 2020 edition of ISO 32000-2, and wasn't implemented in `kernel` yet, so I added it.
 - A bunch of tests, including both round-trip tests and validation tests with known-good files.

Caveats:

 - While I added logic to `PdfSigner` to auto-register the relevant developer extensions when they were "obviously" required, there's a minor issue for ECDSA: from within `signDetached`, there's no convenient way to tell which curve is being used to sign, and in particular whether it appears on the list in ISO/TS 32002. In those cases the caller needs to declare the relevant extension manually.
 - I'm pretty sure that the changes I made to `PdfPKCS7` and friends won't autoport... That's part of the reason why I tried to clean them up as much as humanly possible in one PR, since it's probably less effort to manually port those changes than it would be to get 3 separate PRs with manual porting through the merge pipeline.
 - I probably touched quite a bit of crusty old code with poor test coverage, so I'm sure SonarQube will have plenty to complain about.

Questions, comments, requests, etc. are welcome.

### CODE REVIEW

**Comment by MatthiasValvekens** [comment]
Rebased after the signature migration landed in `develop` today.

**Comment by MatthiasValvekens** [comment]
Since breaking changes are currently allowed on `develop`, I added a commit with some breaking changes to clean up the naming scheme in the API of the `sign` module (as discussed on Slack). The commit message describes the general principles behind the change.

I did this as a separate commit to make it easier to remove in case you'd prefer to go ahead with a "neutral" changeset after all, but if need be I can move it further back into the history so it goes together with the name changes I did in the private API of `PdfPKCS7`.

Side note: the choice of terminology that I'm proposing is only one of several possible alternatives. My main concern is making sure that the API uses the same convention everywhere.

**Comment by vitali-pr** [comment]
PR has been approved and merged.
https://github.com/itext/itext7/commit/97a3598e7b7039531fe3dd0e9ad816ca2447f32a
https://github.com/itext/itext7/commit/cf96cc8b3b5e11c5c877069364a0a22681ce0c53
https://github.com/itext/itext7/commit/de68979bd2364e374c2e07b7649ab94bcfded93f
https://github.com/itext/itext7/commit/19eed450b00dd8541270177c17eedcdf5d0cc0da
https://github.com/itext/itext7/commit/9e65e58c69c47c2f3c0476b10fdddf86b80beb27
https://github.com/itext/itext7/commit/abc23b7c91025a58ad3fcd932bb118943cd3ea46
https://github.com/itext/itext7/commit/1479901ef14d5925fe02f1fbccdfb959d6ab6ace
https://github.com/itext/itext7/commit/81f254f63a638d33665176a460d7b64c0adbd0a2
https://github.com/itext/itext7/commit/cf64547cc16ded273870c7018a2ad40b5abb4619

**Comment by MatthiasValvekens** [comment]
Thanks @vitali-pr ! I'll close this one then. As you may have noticed, I made a follow-up PR for the RSASSA-PSS stuff; see #108. :)

**Pull request closed without merging**
