### PR TITLE
Fix two NPEs

### PR DESCRIPTION
**Pull request by LingMan**
This fixes two separate NPEs that one of my files triggered by simply opening it with a reader and writer and then closing it.

Please note that I don't actually know what the desired behavior for the case fixed in https://github.com/LingMan/itext7/commit/d7de24834f36c0265d2b3277622eeb3579994e48 is. Therefore I've chosen the output to be the same as if content.length was zero.
You could also fix it by adding a NullPointerExcetion clause to the already existing catch block. That would make the code look more concise but be a bit slower. Feel free to change.

### CODE REVIEW

**Comment by blagae** [comment]
Hi @LingMan ,

Could you send your input file to community@itextpdf.com ? While your commits seem very reasonable, we'd like to see what situation exactly is not caught well by iText.

Kind regards,
Benoit

**Comment by LingMan** [comment]
Sample has been sent.

**Comment by ars18wrw** [comment]
The first of your changes seems to be very suitable. However, we're much interested in the second one. As far as we understand our realization, there can be no situation with both value and content set as null. 

Unfortunately, we didn't receive your sample, so could you please just send it again? It'll be much appreciated.

**Comment by LingMan** [comment]
Resent from a different address.

**Comment by amedee** [comment]
We got your file, thank you!

**Comment by ars18wrw** [comment]
Hi @LingMan ,
We studied your sample very carefully and found that the problem is much more difficult. It's connected to objects flushing rather than generating wrong values. We've created a ticket and will investigate this problem as soon as possible.

As for the first part of your PR, I've added changes. Please see https://github.com/itext/itext7/commit/997617790849797222952d6f3ccae995ad89ce66 and close the request.

**Pull request closed without merging**
