### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by LingMan**

### CODE REVIEW

**Comment by amedee** [comment]
Hi @LingMan,

Thank you for your contribution.
These two commits are small comment edits in the same file.
Could you squash them together in one commit and then force push your branch? That will automatically update your Pull Request.

Thank you!

**Comment by LingMan** [comment]
Done.

**Comment by ars18wrw** [comment]
Hi @LingMan,

One more remark before we merge your change. Could you rebase the _comments_ branch, so that it's based on one of the latest develop commits rather than the one dated February, 2018?

Kind regards,
Uladzimir Asipchuk.

**Comment by ars18wrw** [comment]
The changes have been merged: https://github.com/itext/itext7/commit/4e584b3db553b0c95f2302373db4d0a899ad71fc

Thank you for your contribution!

**Pull request closed without merging**
