### PR TITLE
Create SUP tickets from PRs on Github

### PR DESCRIPTION
**Pull request by amedee**
QA-1146

### CODE REVIEW

**Comment by amedee** [comment]
add a comment

**Comment by michaeldemey** [comment]
This is a normal comment.

**Comment by michaeldemey** [comment]
This is a second normal comment.

**Comment by michaeldemey** [comment]
This is a third normal comment.

**Comment by Jakub-iText** [comment]
This is a totally different comment than the ones above.

**Comment by avlemos** [comment]
Here's one too many

**Comment by pkjuak** [comment]
No comment comment

**Comment by SamuelHuylebroeck** [comment]
beating a dead horse comment

**Comment by amedee** [comment]
I have got bad news for you guys... as you can see on https://jira.itextsupport.com/browse/SUP-4132, GitHub comments aren't added to Jira... YET! That's the first thing I'm going to work on _rite nao_.

However I must say that I am very happy that y'all are volunteering to test the living daylights out of this. :-D

**Comment by blagae** [comment]
comment'); DROP TABLE comments; --

**Comment by amedee** [comment]
BY THE WAY @mkl-public this is the GitHub-Jira integration I talked to you about. I'll give you access to SUP-4132 so you can also play around. :)

**Comment by amedee** [comment]
Quoting the quote macro

**Comment by amedee** [comment]
Escaping the quote macro

**Comment by amedee** [comment]
Might work better IF I USE THE CORRECT MACRO SYNTAX #facepalm

**Comment by amedee** [comment]
No visibility restriction for comments

**Comment by amedee** [comment]
and publish changes (again)

Hey guys do you get an email each time I add a comment? You may want to turn that off for a while... :-p

**Comment by avlemos** [comment]
I do <3 now replying via email!

André Lemos

A sexta, 19/04/2019, 13:47, Amedee Van Gasse <notifications@github.com>
escreveu:

**Comment by amedee** [comment]
https://www.youtube.com/watch?v=jbq5dsQ-l9M

**Comment by avlemos** [comment]
image

**Pull request closed without merging**
