### PR TITLE
PdfTrailer#getPageReference throws wrong exceptions.

### PR DESCRIPTION
**Pull request by tohidemyname**
When a negative index is passed to this method, I got an IndexOutOfBoundsException. To my understand, this exception is thrown when an index is too large. I check its code:

 ` public PdfIndirectReference getPageReference(int page) {
        
        if (page < 0)
            throw new IndexOutOfBoundsException(MessageLocalization.getComposedMessage("the.page.number.must.be.gt.eq.1"));
...
 }
`

It shall throw IllegalArgumentException when page is fewer than zero.

### CODE REVIEW

**Comment by Snipx** [comment]
Hi @tohidemyname and thank you for your pull request. Could you branch-off from `develop` and target your pull request to `develop` as well? Right now your pull request has a lot of unrelated commits that are the result of `develop` currently being ahead of `master`.
Thanks!

**Comment by mkl-public** [comment]
> an IndexOutOfBoundsException. To my understand, this exception is thrown when an index is too large.

Why only for a too large index, why not for a too small one? The exception after all is named for the index being out-of-bounds, not above-upper-bound.

Also see the archetypal usage in `java.util.List.get`:

    /**
     * Returns the element at the specified position in this list.
     *
     * @param index index of the element to return
     * @return the element at the specified position in this list
     * @throws IndexOutOfBoundsException if the index is out of range
     *         ({@code index < 0 || index >= size()})
     */
    E get(int index);

**Comment by tohidemyname** [comment]
Indeed, the exception is inconsistent with other methods of itext. For example, com.itextpdf.text.pdf.codec.JBIG2Image#getJbig2Image throws IllegalArgumentException for the same reason:
‘
public static Image getJbig2Image(RandomAccessFileOrArray ra, int page) {
		if (page < 1)
            throw new IllegalArgumentException(MessageLocalization.getComposedMessage("the.page.number.must.be.gt.eq.1"));
		
	}
‘

Another method, com.itextpdf.text.pdf.codec.TiffImage#getTiffImage, also throws IllegalArgumentException:
  public static Image getTiffImage(RandomAccessFileOrArray s, boolean recoverFromImageError, int page, boolean direct) {
        if (page < 1)
throw new IllegalArgumentException(MessageLocalization.getComposedMessage("the.page.number.must.be.gt.eq.1"));

}


When I use itext as a library, I need to catch the exception, but sometimes my code fails to catch it, since it throws different exceptions.

**Comment by Snipx** [comment]
Hi @tohidemyname, please branch-off from develop and target your pull request to develop as well  if you want to make a contribution. Right now your pull request has a lot of unrelated commits that are the result of develop currently being ahead of master.
I am going to close this pull request now but if you have changes to propose in a PR you are very welcome to do so.
Kind regards,
Alexey

**Pull request closed without merging**
