### PR TITLE
Move tfoot after tbody in tags.

### PR DESCRIPTION
**Pull request by rjcohn**
Draw footer after body so that reading order and tags are correct.
In tableTest07 note that the order is now correct in Acrobat's Order
panel and Tags panel.
Note that you see the fixed ordering here in an existing test. In the original,
the footer appeared before "efgh..."
image
Prevent an array index out of range. (Note that the fix on line 1718
now matches the check on line 1714.) I didn't include a test because
the case I ran into depended too much on my code.

### CODE REVIEW

**Comment by ars18wrw** [comment]
Also these changes are correct, such commit will conflict with itext7 border processing mechanism. 
The good news is that there is an appropriate ticket in our backlog so the problem will be fixed when we have time.

**Comment by rjcohn** [comment]
Is there a test case that shows the border problems?

**Comment by ars18wrw** [comment]
Well, I've missed that you propose to process footer after body but _before body borders_. If so everything is indeed fine.

The only problem is that since February 14 we've hugely refactored borders so you should write new pull request or I can just add these changes by myself.

**Comment by rjcohn** [comment]
Thanks. I'll update the pull request later this week.

**Comment by ars18wrw** [comment]
Hi, @rjcohn .
I want you know that we've fixed the issue. 
We also fixed related issue with drawing footer borders after body borders, so it looks like now we collapse footer borders correctly.

**Comment by ars18wrw** [comment]
Take a look at
f358314
8fb688c

**Pull request closed without merging**
