### PR TITLE
Implement CSS-like MIN_WIDTH, MAX_WIDTH for images

### PR DESCRIPTION
**Pull request by rjcohn**
While these properties could apply to other block types (e.g. table
cells), I didn't do that. Note also that Image provides setMinHeight
and setMaxHeight. I didn't add setMinWidth and setMaxWidth in part
because setMinHeight and setMaxHeight set the HEIGHT property, not
MIN_HEIGHT and MAX_HEIGHT, and I don't understand why.

### CODE REVIEW

**Comment by ars18wrw** [comment]
As for MIN_WIDTH/MAX_WIDTH, we have an appropriate ticket (implementation of these properties for all blocks) so we do not think it's right to add such logic partially for Images only. 

As for MAX_HEIGHT/MIN_HEIGHT properties on Images, it looks like we've missed to implement them. I'll add a ticket for it too.

**Comment by ars18wrw** [comment]
Hello, @rjcohn 

About MIN_WIDTH/MAX_WIDTH:
we have an appropriate ticket (implementation of these properties for all blocks) so we do not think it's right to add such logic partially for Images only.

About MAX_HEIGHT/MIN_HEIGHT:
properties on Images, it looks like we've missed to implement them. I'll add a ticket for it too.

Best regards, Uladzimir

**Comment by rjcohn** [comment]
Just to clarify -- MIN_HEIGHT and MAX_HEIGHT are already implemented for images and work fine if you set the property via a Style. However, I was noting that setMinHeight and setMaxHeight set the HEIGHT property and not MIN_ or MAX_. I think that needs to change.

Also, even when you do implement MIN_WIDTH and MAX_WIDTH more generally, you will still need more or less the code I added for images because of the desire to autoscale images.

**Comment by ars18wrw** [comment]
@rjcohn Yes, you were right about heights.  I've fixed it and added a sample.

As for min/max width for images: we will consider your suggested changes for sure, but only in the context of general min/max width implementation ticket.

**Comment by rjcohn** [comment]
Superseded by full implementation of max_width.

**Pull request closed without merging**
