### PR TITLE
Hotfix/background color classcast exception

### PR DESCRIPTION
**Pull request by eamonnmoloney**
Pull request to show background color does not work this PdfA

### CODE REVIEW

**Comment by amedee** [comment]
Hello and thank you for your pull request. Before we examine it further, could you please do the following?

- Squash your 6 commits into one
- Rebase onto the develop branch
- Remove the `$Id$` line

When you have made those changes, force push your branch back to GitHub. This will automatically update your pull request.

**Comment by blagae** [comment]
Hi,

I have looked at the contents of your commit and it looks to me that you have found and solved the bug. However, we will need some more changes than @amedee already suggested, because the reported problem is not related to PDF/A: it is a problem in the layout module itself. Hence, the following actions should be undertaken:

* remove your changes to pdfa/pom.xml
* move your test to the test suite of the layout module, and remove the PDF/A bits
* you don't need the font if you're not making a PDF/A document, and the problem is unrelated to the font logic
* you will need to refactor some of the file paths
* please add the actual compare logic, so that the test can fail by content comparison (not just with exceptions). This is a single line of code e.g. https://github.com/itext/itext7/blob/develop/layout/src/test/java/com/itextpdf/layout/AlignmentTest.java#L54
* you are welcome (though not required) to add a JavaDoc note to the test class that details your authorship

Lots of thanks already for your work !

Benoit

**Comment by amedee** [comment]
Could you please squash your commits into one commit and then force push to update your pull request?
This explains how you do it: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by blagae** [comment]
Hi @eamonnmoloney,

I have looked into this myself because we had a sense of urgency: we are planning to release a new minor version of iText 7 today or tomorrow, and we wanted to include your pull request into the code base. Your commits have been squashed (as requested by Amedee) into one definitive commit, but I preserved your commit messages, and you are still the author of the final commit.

Again thanks for your effort, both in diagnosing and fixing the bug !

Kind regards,
Benoit

**Comment by eamonnmoloney** [comment]
Unfortunately I don't have access to commit on Github in my organisation which is why the commit a a bit... messy... I had to upload them file by file :smiley: 

Great to hear about the release... I'll look out for it!

**Pull request closed without merging**
